<?php
session_start();
if (!isset($_SESSION['user']) || !isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}
include "db.php";
$user_id = $_SESSION['user_id'];
$id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
$format = isset($_GET['format']) ? $_GET['format'] : '';
$sql = "SELECT * FROM persons
        WHERE id='$id'
        AND user_id='$user_id'
        LIMIT 1";
$result = mysqli_query($conn, $sql);
if(mysqli_num_rows($result) == 0){
    die("Student not found!");
}
$row = mysqli_fetch_assoc($result);

/* CSV EXPORT */
if($format == "csv"){
    header("Content-Type: text/csv");
    header("Content-Disposition: attachment; filename=student_".$id.".csv");
    $output = fopen("php://output","w");
    fputcsv($output,["ID","Name","Email","Phone","Department","Semester","Gender"]);
    fputcsv($output,[
        $row['id'],
        $row['name'],
        $row['email'],
        $row['phone'],
        $row['department'],
        $row['semester'],
        $row['gender']
    ]);
    fclose($output);
    exit();
}

/*JSON EXPORT*/
if($format == "json"){
    header("Content-Type: application/json");
    header("Content-Disposition: attachment; filename=student_".$id.".json");
    echo json_encode($row, JSON_PRETTY_PRINT);
    exit();
}

/* PDF EXPORT*/
if($format == "pdf"){
    require('FPDF/fpdf.php');
    class PDF extends FPDF {
        function Header(){
            $this->SetFont('Arial','B',16);
            $this->Cell(0,10,'Student Information Report',0,1,'C');
            $this->Ln(10);
        }
        function Footer(){
            $this->SetY(-15);
            $this->SetFont('Arial','I',10);
            $this->Cell(0,10,'Generated by Student Management System',0,0,'C');
        }
    }
    $pdf = new PDF();
    $pdf->AddPage();
    $pdf->SetFont('Arial','',12);
    $pdf->Cell(40,10,"ID: ".$row['id'],0,1);
    $pdf->Cell(40,10,"Name: ".$row['name'],0,1);
    $pdf->Cell(40,10,"Email: ".$row['email'],0,1);
    $pdf->Cell(40,10,"Phone: ".$row['phone'],0,1);
    $pdf->Cell(40,10,"Department: ".$row['department'],0,1);
    $pdf->Cell(40,10,"Semester: ".$row['semester'],0,1);
    $pdf->Cell(40,10,"Gender: ".$row['gender'],0,1);
    $pdf->Output("D","student_".$id.".pdf");
    exit();
}
echo "Invalid Format!";
?>
